name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black environment
        run: conda create --quiet --name black pyflakes

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black==20.8b1
          black --check django_oci

      - name: Check imports with pyflakes
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          #pyflakes django_oci


  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Download opencontainers/distribution-spec
        uses: actions/checkout@v2
        with:
          repository: opencontainers/distribution-spec
          path: dist-spec

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Set GOPATH
        run: |
          # temporary fix for https://github.com/actions/setup-go/issues/14
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "PATH=$(dirname $GITHUB_WORKSPACE)/bin:${PATH}" >> $GITHUB_PATH

      - name: Compile conformance.test binary
        run: |
          cd dist-spec/conformance
          go mod vendor
          CGO_ENABLED=0 go test -c -o ../../conformance.test
          cd ../../

      - name: Setup Django Test
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -r tests/requirements.txt
          /bin/bash runtests.sh
